<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120319144028 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE planetflow3_domain_model_channel DROP FOREIGN KEY planetflow3_domain_model_channel_ibfk_1");
		$this->addSql("DROP INDEX IDX_7E483DBE9EFA169E ON planetflow3_domain_model_channel");
		$this->addSql("ALTER TABLE planetflow3_domain_model_channel CHANGE planetflow3_category defaultcategory VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE planetflow3_domain_model_channel ADD CONSTRAINT FK_7E483DBE8081A9F9 FOREIGN KEY (defaultcategory) REFERENCES planetflow3_domain_model_category(name)");
		$this->addSql("CREATE INDEX IDX_7E483DBE8081A9F9 ON planetflow3_domain_model_channel (defaultcategory)");
		$this->addSql("ALTER TABLE planetflow3_domain_model_item DROP FOREIGN KEY planetflow3_domain_model_item_ibfk_1");
		$this->addSql("DROP INDEX IDX_65956703C6D66D05 ON planetflow3_domain_model_item");
		$this->addSql("ALTER TABLE planetflow3_domain_model_item CHANGE planetflow3_channel channel VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE planetflow3_domain_model_item ADD CONSTRAINT FK_65956703A2F98E47 FOREIGN KEY (channel) REFERENCES planetflow3_domain_model_channel(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_65956703A2F98E47 ON planetflow3_domain_model_item (channel)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE planetflow3_domain_model_channel DROP FOREIGN KEY FK_7E483DBE8081A9F9");
		$this->addSql("DROP INDEX IDX_7E483DBE8081A9F9 ON planetflow3_domain_model_channel");
		$this->addSql("ALTER TABLE planetflow3_domain_model_channel CHANGE defaultcategory planetflow3_category VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE planetflow3_domain_model_channel ADD CONSTRAINT planetflow3_domain_model_channel_ibfk_1 FOREIGN KEY (planetflow3_category) REFERENCES planetflow3_domain_model_category(name)");
		$this->addSql("CREATE INDEX IDX_7E483DBE9EFA169E ON planetflow3_domain_model_channel (planetflow3_category)");
		$this->addSql("ALTER TABLE planetflow3_domain_model_item DROP FOREIGN KEY FK_65956703A2F98E47");
		$this->addSql("DROP INDEX IDX_65956703A2F98E47 ON planetflow3_domain_model_item");
		$this->addSql("ALTER TABLE planetflow3_domain_model_item CHANGE channel planetflow3_channel VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE planetflow3_domain_model_item ADD CONSTRAINT planetflow3_domain_model_item_ibfk_1 FOREIGN KEY (planetflow3_channel) REFERENCES planetflow3_domain_model_channel(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_65956703C6D66D05 ON planetflow3_domain_model_item (planetflow3_channel)");
	}
}

?>